export { default as HeroSection } from './hero-section';
export { default as FeaturesSection } from './features-section';
export { default as HowItWorksSection } from './how-it-works-section';
export { default as PricingSection } from './pricing-section';
export { default as PartnershipSection } from './partnership-section';
export { default as TeamSection } from './team-section';
export { default as QuoteSection } from './quote-section';
export { default as CtaSection } from './cta-section';
export { default as FooterSection } from './footer-section';
